import type { SiteLocale } from '../../lib/siteLocale';
import type { WorkFormError } from './form';

// ─── copy ────────────────────────────────────────────────────────────────────

const pt = {
  title: 'Trabalhos realizados',
  intro: 'Registre os trabalhos já realizados pela sua igreja, com participantes, Daime e contribuições.',
  introAdmin: 'Registros de trabalhos de todas as igrejas. Revise-os e gerencie quem pode registrar.',
  loading: 'Carregando...',
  loadError: 'Erro ao carregar os registros.',
  noPermission: 'Esta área é para os gestores das igrejas. Peça a um administrador para vincular sua conta a uma igreja.',
  tabs: { records: 'Registros', managers: 'Gestores das igrejas', workTypes: 'Tipos de trabalho' },

  newRecord: 'Registrar trabalho',
  editRecord: 'Editar registro',
  sectionWork: 'Trabalho',
  sectionParticipants: 'Participantes',
  sectionDaime: 'Daime',
  sectionContributions: 'Contribuições',
  church: 'Igreja',
  selectChurch: 'Selecionar igreja...',
  date: 'Data',
  workType: 'Trabalho',
  selectWorkType: 'Selecionar trabalho...',
  officialCalendar: 'Calendário oficial',
  otherWorks: 'Outros trabalhos',
  other: 'Outro',
  workTypeOther: 'Qual trabalho?',
  venue: 'Local',
  hymnal: 'Hinário',
  optional: 'opcional',
  totalAttendees: 'Total de participantes',
  initiatedAttendees: 'Fardados',
  whiteAttendees: 'Não fardados',
  computed: 'calculado',
  sacramentItem: 'Daime usado',
  selectBatch: 'Selecionar lote...',
  quantity: 'Quantidade',
  balance: 'saldo',
  noLinkedStock: 'Nenhum estoque de Daime está vinculado a esta igreja. Peça a um administrador para vincular um na página Sacramento.',
  aboveBalance: 'A quantidade supera o saldo registrado deste lote.',
  contributionsCollected: 'Total de contribuições recebidas',
  icefluBrazilQuota: 'Cota para a ICEFLU Brasil',
  icefluBrazilQuotaHint: 'incluindo o feitio',
  save: 'Salvar registro',
  saving: 'Salvando...',
  cancel: 'Cancelar',
  saved: 'Registro salvo.',
  saveError: 'Erro ao salvar o registro.',
  fixErrors: 'Corrija os campos destacados.',

  records: 'Registros',
  noRecords: 'Nenhum trabalho registrado ainda.',
  allChurches: 'Todas as igrejas',
  allStatuses: 'Todos os estados',
  allYears: 'Todos os anos',
  totals: 'Totais',
  works: 'trabalhos',
  preApproved: 'Pré-aprovado',
  reviewed: 'Revisado e aprovado',
  markReviewed: 'Marcar como revisado',
  unmarkReviewed: 'Voltar a pré-aprovado',
  edit: 'Editar',
  delete: 'Excluir',
  deleting: 'Excluindo...',
  confirmDelete: 'Excluir este registro? O Daime volta ao estoque.',
  confirmEditReviewed: 'Este registro já foi revisado. Ao salvar alterações ele volta a pré-aprovado. Continuar?',
  actionError: 'A operação falhou.',

  managersTitle: 'Gestores das igrejas',
  managersIntro: 'Contas vinculadas a uma igreja registram os trabalhos dela e usam o Daime dos estoques vinculados a ela.',
  account: 'Conta',
  selectAccount: 'Selecionar conta...',
  churches: 'Igrejas',
  addManager: 'Adicionar gestor',
  saveManager: 'Salvar',
  removeManager: 'Remover',
  confirmRemoveManager: 'Remover todas as igrejas desta conta?',
  noManagers: 'Nenhuma conta vinculada a igrejas.',

  workTypesTitle: 'Tipos de trabalho',
  workTypesIntro: 'Opções do menu "Trabalho". Tipos desativados não aparecem em novos registros; os registros existentes mantêm o nome.',
  draftNotice: 'Rascunho inicial, ainda não revisado: confira a lista e salve para publicá-la.',
  label: 'Nome',
  category: 'Grupo',
  active: 'Ativo',
  moveUp: 'Subir',
  moveDown: 'Descer',
  remove: 'Remover',
  addWorkType: 'Adicionar tipo',
  saveWorkTypes: 'Salvar lista',
  workTypesSaved: 'Lista salva.',
  otherAlwaysOffered: '"Outro", com descrição livre, é sempre oferecido no fim do menu.',

  errors: {
    church: 'Selecione a igreja.',
    date: 'Informe a data.',
    dateInFuture: 'A data não pode ser futura.',
    workType: 'Selecione o trabalho.',
    workTypeOther: 'Descreva o trabalho.',
    totalAttendees: 'Informe um número inteiro.',
    initiatedAttendees: 'Informe um número inteiro.',
    initiatedAboveTotal: 'Os fardados não podem superar o total.',
    sacramentItem: 'Selecione o lote de Daime.',
    sacramentQuantity: 'Informe uma quantidade maior que zero.',
    contributionsCollected: 'Informe um valor (0 se nenhum).',
    icefluBrazilQuota: 'Informe um valor (0 se nenhum).'
  } satisfies Record<WorkFormError, string>
};

export type WorksCopy = typeof pt;

const en: WorksCopy = {
  title: 'Completed works',
  intro: 'Record the works your church has held, with participants, Daime, and contributions.',
  introAdmin: 'Work records from every church. Review them and manage who can record.',
  loading: 'Loading...',
  loadError: 'Could not load the records.',
  noPermission: 'This area is for church managers. Ask an administrator to link your account to a church.',
  tabs: { records: 'Records', managers: 'Church managers', workTypes: 'Work types' },

  newRecord: 'Record a work',
  editRecord: 'Edit record',
  sectionWork: 'Work',
  sectionParticipants: 'Participants',
  sectionDaime: 'Daime',
  sectionContributions: 'Contributions',
  church: 'Church',
  selectChurch: 'Select church...',
  date: 'Date',
  workType: 'Work',
  selectWorkType: 'Select work...',
  officialCalendar: 'Official calendar',
  otherWorks: 'Other works',
  other: 'Other',
  workTypeOther: 'Which work?',
  venue: 'Place',
  hymnal: 'Hymnal',
  optional: 'optional',
  totalAttendees: 'Total participants',
  initiatedAttendees: 'Fardados',
  whiteAttendees: 'Non-fardados',
  computed: 'calculated',
  sacramentItem: 'Daime used',
  selectBatch: 'Select batch...',
  quantity: 'Quantity',
  balance: 'balance',
  noLinkedStock: 'No Daime stock is linked to this church. Ask an administrator to link one on the Sacrament page.',
  aboveBalance: 'The quantity exceeds this batch\'s recorded balance.',
  contributionsCollected: 'Total contributions collected',
  icefluBrazilQuota: 'Share for ICEFLU Brazil',
  icefluBrazilQuotaHint: 'including feitio',
  save: 'Save record',
  saving: 'Saving...',
  cancel: 'Cancel',
  saved: 'Record saved.',
  saveError: 'Could not save the record.',
  fixErrors: 'Fix the highlighted fields.',

  records: 'Records',
  noRecords: 'No works recorded yet.',
  allChurches: 'All churches',
  allStatuses: 'All statuses',
  allYears: 'All years',
  totals: 'Totals',
  works: 'works',
  preApproved: 'Pre-approved',
  reviewed: 'Reviewed and approved',
  markReviewed: 'Mark reviewed',
  unmarkReviewed: 'Back to pre-approved',
  edit: 'Edit',
  delete: 'Delete',
  deleting: 'Deleting...',
  confirmDelete: 'Delete this record? The Daime goes back to the stock.',
  confirmEditReviewed: 'This record was already reviewed. Saving changes sends it back to pre-approved. Continue?',
  actionError: 'The operation failed.',

  managersTitle: 'Church managers',
  managersIntro: 'Accounts linked to a church record its works and draw Daime from the stocks linked to it.',
  account: 'Account',
  selectAccount: 'Select account...',
  churches: 'Churches',
  addManager: 'Add manager',
  saveManager: 'Save',
  removeManager: 'Remove',
  confirmRemoveManager: 'Remove all churches from this account?',
  noManagers: 'No accounts are linked to churches.',

  workTypesTitle: 'Work types',
  workTypesIntro: 'Options of the "Work" menu. Inactive types are hidden from new records; existing records keep their name.',
  draftNotice: 'Initial draft, not yet reviewed: check the list and save it to publish.',
  label: 'Name',
  category: 'Group',
  active: 'Active',
  moveUp: 'Up',
  moveDown: 'Down',
  remove: 'Remove',
  addWorkType: 'Add type',
  saveWorkTypes: 'Save list',
  workTypesSaved: 'List saved.',
  otherAlwaysOffered: '"Other", with a free description, is always offered at the end of the menu.',

  errors: {
    church: 'Select the church.',
    date: 'Enter the date.',
    dateInFuture: 'The date cannot be in the future.',
    workType: 'Select the work.',
    workTypeOther: 'Describe the work.',
    totalAttendees: 'Enter a whole number.',
    initiatedAttendees: 'Enter a whole number.',
    initiatedAboveTotal: 'Fardados cannot exceed the total.',
    sacramentItem: 'Select the Daime batch.',
    sacramentQuantity: 'Enter a quantity above zero.',
    contributionsCollected: 'Enter an amount (0 if none).',
    icefluBrazilQuota: 'Enter an amount (0 if none).'
  }
};

const es: WorksCopy = {
  title: 'Trabajos realizados',
  intro: 'Registre los trabajos ya realizados por su iglesia, con participantes, Daime y contribuciones.',
  introAdmin: 'Registros de trabajos de todas las iglesias. Revíselos y gestione quién puede registrar.',
  loading: 'Cargando...',
  loadError: 'Error al cargar los registros.',
  noPermission: 'Esta área es para los gestores de las iglesias. Pida a un administrador que vincule su cuenta a una iglesia.',
  tabs: { records: 'Registros', managers: 'Gestores de las iglesias', workTypes: 'Tipos de trabajo' },

  newRecord: 'Registrar trabajo',
  editRecord: 'Editar registro',
  sectionWork: 'Trabajo',
  sectionParticipants: 'Participantes',
  sectionDaime: 'Daime',
  sectionContributions: 'Contribuciones',
  church: 'Iglesia',
  selectChurch: 'Seleccionar iglesia...',
  date: 'Fecha',
  workType: 'Trabajo',
  selectWorkType: 'Seleccionar trabajo...',
  officialCalendar: 'Calendario oficial',
  otherWorks: 'Otros trabajos',
  other: 'Otro',
  workTypeOther: '¿Qué trabajo?',
  venue: 'Lugar',
  hymnal: 'Himnario',
  optional: 'opcional',
  totalAttendees: 'Total de participantes',
  initiatedAttendees: 'Fardados',
  whiteAttendees: 'No fardados',
  computed: 'calculado',
  sacramentItem: 'Daime usado',
  selectBatch: 'Seleccionar lote...',
  quantity: 'Cantidad',
  balance: 'saldo',
  noLinkedStock: 'Ningún stock de Daime está vinculado a esta iglesia. Pida a un administrador que vincule uno en la página Sacramento.',
  aboveBalance: 'La cantidad supera el saldo registrado de este lote.',
  contributionsCollected: 'Total de contribuciones recibidas',
  icefluBrazilQuota: 'Cuota para ICEFLU Brasil',
  icefluBrazilQuotaHint: 'incluido el feitio',
  save: 'Guardar registro',
  saving: 'Guardando...',
  cancel: 'Cancelar',
  saved: 'Registro guardado.',
  saveError: 'Error al guardar el registro.',
  fixErrors: 'Corrija los campos resaltados.',

  records: 'Registros',
  noRecords: 'Todavía no hay trabajos registrados.',
  allChurches: 'Todas las iglesias',
  allStatuses: 'Todos los estados',
  allYears: 'Todos los años',
  totals: 'Totales',
  works: 'trabajos',
  preApproved: 'Preaprobado',
  reviewed: 'Revisado y aprobado',
  markReviewed: 'Marcar como revisado',
  unmarkReviewed: 'Volver a preaprobado',
  edit: 'Editar',
  delete: 'Eliminar',
  deleting: 'Eliminando...',
  confirmDelete: '¿Eliminar este registro? El Daime vuelve al stock.',
  confirmEditReviewed: 'Este registro ya fue revisado. Al guardar cambios vuelve a preaprobado. ¿Continuar?',
  actionError: 'La operación falló.',

  managersTitle: 'Gestores de las iglesias',
  managersIntro: 'Las cuentas vinculadas a una iglesia registran sus trabajos y usan el Daime de los stocks vinculados a ella.',
  account: 'Cuenta',
  selectAccount: 'Seleccionar cuenta...',
  churches: 'Iglesias',
  addManager: 'Añadir gestor',
  saveManager: 'Guardar',
  removeManager: 'Quitar',
  confirmRemoveManager: '¿Quitar todas las iglesias de esta cuenta?',
  noManagers: 'Ninguna cuenta está vinculada a iglesias.',

  workTypesTitle: 'Tipos de trabajo',
  workTypesIntro: 'Opciones del menú "Trabajo". Los tipos desactivados no aparecen en nuevos registros; los existentes conservan el nombre.',
  draftNotice: 'Borrador inicial, aún no revisado: revise la lista y guárdela para publicarla.',
  label: 'Nombre',
  category: 'Grupo',
  active: 'Activo',
  moveUp: 'Subir',
  moveDown: 'Bajar',
  remove: 'Quitar',
  addWorkType: 'Añadir tipo',
  saveWorkTypes: 'Guardar lista',
  workTypesSaved: 'Lista guardada.',
  otherAlwaysOffered: '"Otro", con descripción libre, siempre se ofrece al final del menú.',

  errors: {
    church: 'Seleccione la iglesia.',
    date: 'Indique la fecha.',
    dateInFuture: 'La fecha no puede ser futura.',
    workType: 'Seleccione el trabajo.',
    workTypeOther: 'Describa el trabajo.',
    totalAttendees: 'Indique un número entero.',
    initiatedAttendees: 'Indique un número entero.',
    initiatedAboveTotal: 'Los fardados no pueden superar el total.',
    sacramentItem: 'Seleccione el lote de Daime.',
    sacramentQuantity: 'Indique una cantidad mayor que cero.',
    contributionsCollected: 'Indique un importe (0 si no hay).',
    icefluBrazilQuota: 'Indique un importe (0 si no hay).'
  }
};

const it: WorksCopy = {
  title: 'Lavori fatti',
  intro: 'Registra i lavori già svolti dalla tua chiesa, con partecipanti, Daime e contributi.',
  introAdmin: 'Registri dei lavori di tutte le chiese. Revisionali e gestisci chi può registrarli.',
  loading: 'Caricamento...',
  loadError: 'Errore nel caricamento dei registri.',
  noPermission: 'Quest\'area è per i gestori delle chiese. Chiedi a un amministratore di collegare il tuo account a una chiesa.',
  tabs: { records: 'Registri', managers: 'Gestori delle chiese', workTypes: 'Tipi di lavoro' },

  newRecord: 'Registra lavoro',
  editRecord: 'Modifica registro',
  sectionWork: 'Lavoro',
  sectionParticipants: 'Partecipanti',
  sectionDaime: 'Daime',
  sectionContributions: 'Contributi',
  church: 'Chiesa',
  selectChurch: 'Seleziona chiesa...',
  date: 'Data',
  workType: 'Lavoro',
  selectWorkType: 'Seleziona lavoro...',
  officialCalendar: 'Calendario ufficiale',
  otherWorks: 'Altri lavori',
  other: 'Altro',
  workTypeOther: 'Quale lavoro?',
  venue: 'Luogo',
  hymnal: 'Innario',
  optional: 'facoltativo',
  totalAttendees: 'Totale partecipanti',
  initiatedAttendees: 'Fardati',
  whiteAttendees: 'Bianchi',
  computed: 'calcolato',
  sacramentItem: 'Daime usato',
  selectBatch: 'Seleziona lotto...',
  quantity: 'Quantità',
  balance: 'saldo',
  noLinkedStock: 'Nessuno stock di Daime è collegato a questa chiesa. Chiedi a un amministratore di collegarne uno nella pagina Sacramento.',
  aboveBalance: 'La quantità supera il saldo registrato di questo lotto.',
  contributionsCollected: 'Totale contributi raccolti',
  icefluBrazilQuota: 'Quota per ICEFLU Brasile',
  icefluBrazilQuotaHint: 'incluso feitio',
  save: 'Salva registro',
  saving: 'Salvataggio...',
  cancel: 'Annulla',
  saved: 'Registro salvato.',
  saveError: 'Errore nel salvataggio del registro.',
  fixErrors: 'Correggi i campi evidenziati.',

  records: 'Registri',
  noRecords: 'Nessun lavoro registrato.',
  allChurches: 'Tutte le chiese',
  allStatuses: 'Tutti gli stati',
  allYears: 'Tutti gli anni',
  totals: 'Totali',
  works: 'lavori',
  preApproved: 'Pre-approvato',
  reviewed: 'Revisionato e approvato',
  markReviewed: 'Segna come revisionato',
  unmarkReviewed: 'Torna a pre-approvato',
  edit: 'Modifica',
  delete: 'Elimina',
  deleting: 'Eliminazione...',
  confirmDelete: 'Eliminare questo registro? Il Daime torna nello stock.',
  confirmEditReviewed: 'Questo registro è già stato revisionato. Salvando le modifiche torna pre-approvato. Continuare?',
  actionError: 'L\'operazione non è riuscita.',

  managersTitle: 'Gestori delle chiese',
  managersIntro: 'Gli account collegati a una chiesa registrano i suoi lavori e usano il Daime degli stock collegati a essa.',
  account: 'Account',
  selectAccount: 'Seleziona account...',
  churches: 'Chiese',
  addManager: 'Aggiungi gestore',
  saveManager: 'Salva',
  removeManager: 'Rimuovi',
  confirmRemoveManager: 'Rimuovere tutte le chiese da questo account?',
  noManagers: 'Nessun account è collegato a chiese.',

  workTypesTitle: 'Tipi di lavoro',
  workTypesIntro: 'Voci del menu "Lavoro". I tipi disattivati non compaiono nei nuovi registri; quelli esistenti mantengono il nome.',
  draftNotice: 'Bozza iniziale, non ancora revisionata: controlla l\'elenco e salvalo per pubblicarlo.',
  label: 'Nome',
  category: 'Gruppo',
  active: 'Attivo',
  moveUp: 'Su',
  moveDown: 'Giù',
  remove: 'Rimuovi',
  addWorkType: 'Aggiungi tipo',
  saveWorkTypes: 'Salva elenco',
  workTypesSaved: 'Elenco salvato.',
  otherAlwaysOffered: '"Altro", con descrizione libera, è sempre offerto in fondo al menu.',

  errors: {
    church: 'Seleziona la chiesa.',
    date: 'Indica la data.',
    dateInFuture: 'La data non può essere futura.',
    workType: 'Seleziona il lavoro.',
    workTypeOther: 'Descrivi il lavoro.',
    totalAttendees: 'Indica un numero intero.',
    initiatedAttendees: 'Indica un numero intero.',
    initiatedAboveTotal: 'I fardati non possono superare il totale.',
    sacramentItem: 'Seleziona il lotto di Daime.',
    sacramentQuantity: 'Indica una quantità maggiore di zero.',
    contributionsCollected: 'Indica un importo (0 se nessuno).',
    icefluBrazilQuota: 'Indica un importo (0 se nessuno).'
  }
};

export const worksCopyByLocale: Record<SiteLocale, WorksCopy> = { pt, en, es, it };

export const numberLocaleBySite: Record<SiteLocale, string> = {
  pt: 'pt-BR',
  en: 'en-GB',
  es: 'es-ES',
  it: 'it-IT'
};
