import type { ChurchesCopy } from '../churches/ChurchesSections';

// ─── copy ────────────────────────────────────────────────────────────────────

export const copyByLocale = {
  pt: {
    title: 'Sacramento',
    intro: 'Estoques de Daime com entradas, saídas e rastreabilidade por lote e localização.',
    newStock: 'Novo Estoque',
    stockName: 'Nome do estoque',
    stockLocation: 'Localização',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    editStock: 'Editar estoque',
    editBatch: 'Editar lote',
    delete: 'Excluir',
    confirmDelete: 'Excluir este item?',
    loading: 'Carregando...',
    noStocks: 'Nenhum estoque cadastrado ainda.',
    noItems: 'Nenhum lote neste estoque.',
    noTransactions: 'Nenhuma movimentação registrada.',
    newItem: 'Novo Lote',
    degree: 'Grau',
    concentration: 'Concentração',
    form: 'Forma',
    liquid: 'Líquida',
    gel: 'Gel',
    originChurch: 'Casa de Feitio',
    selectChurch: 'Selecionar igreja...',
    selectCasa: 'Selecionar casa...',
    addChurch: 'Cadastrar nova igreja',
    responsiblePerson: 'Responsável',
    feitioDate: 'Data do feitio',
    feitioPeriod: 'Período de feitio',
    feitioSingle: 'Data única',
    feitioFrom: 'De',
    feitioTo: 'Até',
    currentBalance: 'Saldo atual',
    liters: 'L',
    kg: 'kg',
    logMovement: 'Registrar Movimento',
    movements: 'Movimentações',
    movementType: 'Tipo',
    entry: 'Entrada',
    exit: 'Saída',
    date: 'Data',
    missionary: 'Missionário',
    destinationChurch: 'Igreja de destino',
    quantity: 'Quantidade',
    notes: 'Observações',
    saving: 'Salvando...',
    deleting: 'Excluindo...',
    showMovements: 'Ver movimentações',
    hideMovements: 'Ocultar movimentações',
    editMovement: 'Editar',
    deleteMovement: 'Excluir',
    confirmDeleteMovement: 'Excluir este movimento?',
  },
  en: {
    title: 'Sacrament',
    intro: 'Daime inventory with entries, exits, and traceability by batch and location.',
    newStock: 'New Stock',
    stockName: 'Stock name',
    stockLocation: 'Location',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    editStock: 'Edit stock',
    editBatch: 'Edit batch',
    delete: 'Delete',
    confirmDelete: 'Delete this item?',
    loading: 'Loading...',
    noStocks: 'No stocks registered yet.',
    noItems: 'No batches in this stock.',
    noTransactions: 'No transactions logged.',
    newItem: 'New Batch',
    degree: 'Degree',
    concentration: 'Concentration',
    form: 'Form',
    liquid: 'Liquid',
    gel: 'Gel',
    originChurch: 'Casa de Feitio',
    selectChurch: 'Select church...',
    selectCasa: 'Select casa...',
    addChurch: 'Create new church',
    responsiblePerson: 'Responsible',
    feitioDate: 'Feitio date',
    feitioPeriod: 'Feitio period',
    feitioSingle: 'Single date',
    feitioFrom: 'From',
    feitioTo: 'To',
    currentBalance: 'Current balance',
    liters: 'L',
    kg: 'kg',
    logMovement: 'Log Movement',
    movements: 'Movements',
    movementType: 'Type',
    entry: 'Entry',
    exit: 'Exit',
    date: 'Date',
    missionary: 'Missionary',
    destinationChurch: 'Destination church',
    quantity: 'Quantity',
    notes: 'Notes',
    saving: 'Saving...',
    deleting: 'Deleting...',
    showMovements: 'Show movements',
    hideMovements: 'Hide movements',
    editMovement: 'Edit',
    deleteMovement: 'Delete',
    confirmDeleteMovement: 'Delete this movement?',
  },
  es: {
    title: 'Sacramento',
    intro: 'Inventario de Daime con entradas, salidas y trazabilidad por lote y ubicación.',
    newStock: 'Nueva Existencia',
    stockName: 'Nombre de la existencia',
    stockLocation: 'Ubicación',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    editStock: 'Editar existencia',
    editBatch: 'Editar lote',
    delete: 'Eliminar',
    confirmDelete: '¿Eliminar este elemento?',
    loading: 'Cargando...',
    noStocks: 'Todavía no hay existencias registradas.',
    noItems: 'No hay lotes en esta existencia.',
    noTransactions: 'No hay movimientos registrados.',
    newItem: 'Nuevo Lote',
    degree: 'Grado',
    concentration: 'Concentración',
    form: 'Forma',
    liquid: 'Líquida',
    gel: 'Gel',
    originChurch: 'Casa de Feitio',
    selectChurch: 'Seleccionar iglesia...',
    selectCasa: 'Seleccionar casa...',
    addChurch: 'Registrar nueva iglesia',
    responsiblePerson: 'Responsable',
    feitioDate: 'Fecha del feitio',
    feitioPeriod: 'Período del feitio',
    feitioSingle: 'Fecha única',
    feitioFrom: 'Desde',
    feitioTo: 'Hasta',
    currentBalance: 'Saldo actual',
    liters: 'L',
    kg: 'kg',
    logMovement: 'Registrar Movimiento',
    movements: 'Movimientos',
    movementType: 'Tipo',
    entry: 'Entrada',
    exit: 'Salida',
    date: 'Fecha',
    missionary: 'Misionero',
    destinationChurch: 'Iglesia de destino',
    quantity: 'Cantidad',
    notes: 'Observaciones',
    saving: 'Guardando...',
    deleting: 'Eliminando...',
    showMovements: 'Ver movimientos',
    hideMovements: 'Ocultar movimientos',
    editMovement: 'Editar',
    deleteMovement: 'Eliminar',
    confirmDeleteMovement: '¿Eliminar este movimiento?',
  },
  it: {
    title: 'Sacramento',
    intro: 'Inventario del Daime con entrate, uscite e tracciabilità per lotto e posizione.',
    newStock: 'Nuova Scorta',
    stockName: 'Nome della scorta',
    stockLocation: 'Posizione',
    save: 'Salva',
    cancel: 'Annulla',
    edit: 'Modifica',
    editStock: 'Modifica scorta',
    editBatch: 'Modifica lotto',
    delete: 'Elimina',
    confirmDelete: 'Eliminare questo elemento?',
    loading: 'Caricamento...',
    noStocks: 'Nessuna scorta registrata.',
    noItems: 'Nessun lotto in questa scorta.',
    noTransactions: 'Nessun movimento registrato.',
    newItem: 'Nuovo Lotto',
    degree: 'Grado',
    concentration: 'Concentrazione',
    form: 'Forma',
    liquid: 'Liquida',
    gel: 'Gel',
    originChurch: 'Casa de Feitio',
    selectChurch: 'Seleziona chiesa...',
    selectCasa: 'Seleziona casa...',
    addChurch: 'Registra nuova chiesa',
    responsiblePerson: 'Responsabile',
    feitioDate: 'Data del feitio',
    feitioPeriod: 'Periodo del feitio',
    feitioSingle: 'Data singola',
    feitioFrom: 'Dal',
    feitioTo: 'Al',
    currentBalance: 'Saldo attuale',
    liters: 'L',
    kg: 'kg',
    logMovement: 'Registra Movimento',
    movements: 'Movimenti',
    movementType: 'Tipo',
    entry: 'Entrata',
    exit: 'Uscita',
    date: 'Data',
    missionary: 'Missionario',
    destinationChurch: 'Chiesa di destinazione',
    quantity: 'Quantità',
    notes: 'Osservazioni',
    saving: 'Salvataggio...',
    deleting: 'Eliminazione...',
    showMovements: 'Mostra movimenti',
    hideMovements: 'Nascondi movimenti',
    editMovement: 'Modifica',
    deleteMovement: 'Elimina',
    confirmDeleteMovement: 'Eliminare questo movimento?',
  },
} as const;

export type SacramentLocale = keyof typeof copyByLocale;
export type Copy = { [K in keyof typeof copyByLocale.pt]: string };

export const churchFormCopyByLocale: Record<SacramentLocale, ChurchesCopy> = {
  pt: { newChurch: 'Nova igreja', formHint: 'Preencha o nome e, se quiser, localização, linhagem e coordenadas (para mapa).', editing: 'Editando', loginToSave: 'Faça login para salvar', name: 'Nome', lineage: 'Linhagem / casa', city: 'Cidade', state: 'Estado', country: 'País', leader: 'Dirigente', leaderEmail: 'Email do dirigente', churchEmail: 'Email da igreja', latitude: 'Latitude', longitude: 'Longitude', notes: 'Observações', saveChanges: 'Salvar alterações', createChurch: 'Cadastrar igreja', saving: 'Salvando...', cancelEdit: 'Cancelar edição', saved: 'Salvo.', map: 'Ver no mapa', works: 'Trabalhos', local: 'Local', responsible: 'Responsável', people: 'Pessoas', current: 'Atuais', initiation: 'Fardamento', edit: 'Editar', deleting: 'Excluindo...', delete: 'Excluir', churchesRegistered: 'Igrejas cadastradas', loading: 'Carregando...', noChurches: 'Nenhuma igreja cadastrada ainda.' },
  en: { newChurch: 'New church', formHint: 'Fill in the name and, if desired, location, lineage, and coordinates (for maps).', editing: 'Editing', loginToSave: 'Sign in to save', name: 'Name', lineage: 'Lineage / house', city: 'City', state: 'State', country: 'Country', leader: 'Leader', leaderEmail: 'Leader email', churchEmail: 'Church email', latitude: 'Latitude', longitude: 'Longitude', notes: 'Notes', saveChanges: 'Save changes', createChurch: 'Create church', saving: 'Saving...', cancelEdit: 'Cancel edit', saved: 'Saved.', map: 'View on map', works: 'Works', local: 'Location', responsible: 'Responsible', people: 'People', current: 'Current', initiation: 'Fardamento', edit: 'Edit', deleting: 'Deleting...', delete: 'Delete', churchesRegistered: 'Registered churches', loading: 'Loading...', noChurches: 'No churches registered yet.' },
  es: { newChurch: 'Nueva iglesia', formHint: 'Complete el nombre y, si quiere, ubicación, linaje y coordenadas (para el mapa).', editing: 'Editando', loginToSave: 'Inicie sesión para guardar', name: 'Nombre', lineage: 'Linaje / casa', city: 'Ciudad', state: 'Estado', country: 'País', leader: 'Dirigente', leaderEmail: 'Email del dirigente', churchEmail: 'Email de la iglesia', latitude: 'Latitud', longitude: 'Longitud', notes: 'Observaciones', saveChanges: 'Guardar cambios', createChurch: 'Registrar iglesia', saving: 'Guardando...', cancelEdit: 'Cancelar edición', saved: 'Guardado.', map: 'Ver en el mapa', works: 'Trabajos', local: 'Local', responsible: 'Responsable', people: 'Personas', current: 'Actuales', initiation: 'Fardamento', edit: 'Editar', deleting: 'Eliminando...', delete: 'Eliminar', churchesRegistered: 'Iglesias registradas', loading: 'Cargando...', noChurches: 'Todavía no hay iglesias registradas.' },
  it: { newChurch: 'Nuova chiesa', formHint: 'Compila il nome e, se vuoi, posizione, linea e coordinate (per la mappa).', editing: 'Modifica', loginToSave: 'Accedi per salvare', name: 'Nome', lineage: 'Linea / casa', city: 'Città', state: 'Stato', country: 'Paese', leader: 'Dirigente', leaderEmail: 'Email del dirigente', churchEmail: 'Email della chiesa', latitude: 'Latitudine', longitude: 'Longitudine', notes: 'Osservazioni', saveChanges: 'Salva modifiche', createChurch: 'Registra chiesa', saving: 'Salvataggio...', cancelEdit: 'Annulla modifica', saved: 'Salvato.', map: 'Vedi sulla mappa', works: 'Lavori', local: 'Luogo', responsible: 'Responsabile', people: 'Persone', current: 'Attuali', initiation: 'Fardamento', edit: 'Modifica', deleting: 'Eliminazione...', delete: 'Elimina', churchesRegistered: 'Chiese registrate', loading: 'Caricamento...', noChurches: 'Nessuna chiesa registrata.' },
};

export const requiredChurchNameByLocale: Record<SacramentLocale, string> = {
  pt: 'Nome é obrigatório',
  en: 'Name is required',
  es: 'El nombre es obligatorio',
  it: 'Il nome è obbligatorio',
};
