import type { DonationMethod, DonationReason } from '../../lib/donations';
import type { SiteLocale } from '../../lib/siteLocale';
import type { DonationFormError } from './form';

// ─── copy ────────────────────────────────────────────────────────────────────

const pt = {
  title: 'Doações à ICEFLU Brasil',
  intro: 'Registre as doações que sua igreja enviou à ICEFLU Brasil, com o comprovante.',
  introAdmin: 'Doações enviadas à ICEFLU Brasil por todas as igrejas. Revise-as e confira os comprovantes.',
  managersHint: 'Quem pode registrar doações são os gestores das igrejas, atribuídos em Trabalhos → Gestores das igrejas.',
  loading: 'Carregando...',
  loadError: 'Erro ao carregar as doações.',
  noPermission: 'Esta área é para os gestores das igrejas. Peça a um administrador para vincular sua conta a uma igreja.',

  newDonation: 'Registrar doação',
  editDonation: 'Editar doação',
  church: 'Igreja',
  selectChurch: 'Selecionar igreja...',
  date: 'Data',
  amount: 'Valor (€)',
  reason: 'Motivo',
  selectReason: 'Selecionar motivo...',
  reasons: { feitio: 'Cobertura do feitio', membership: 'Associativo', jurua: 'Juruá' } satisfies Record<DonationReason, string>,
  recipient: 'Destinatário',
  recipientPlaceholder: 'Quem recebeu a doação',
  method: 'Forma de envio',
  methods: { 'bank-transfer': 'Transferência bancária', 'in-person': 'Em mãos' } satisfies Record<DonationMethod, string>,
  receipt: { 'bank-transfer': 'Comprovante bancário', 'in-person': 'Recibo do destinatário' } satisfies Record<DonationMethod, string>,
  receiptPending: 'Comprovante',
  receiptPickMethod: 'Escolha a forma de envio: transferência pede o comprovante bancário; em mãos, o recibo assinado pelo destinatário.',
  currentReceipt: 'Comprovante atual',
  replaceReceiptHint: 'Envie um arquivo só se quiser substituí-lo.',
  save: 'Salvar doação',
  saving: 'Salvando...',
  cancel: 'Cancelar',
  saved: 'Doação salva.',
  saveError: 'Erro ao salvar a doação.',
  fixErrors: 'Corrija os campos destacados.',

  donations: 'Doações',
  noDonations: 'Nenhuma doação registrada ainda.',
  allChurches: 'Todas as igrejas',
  allStatuses: 'Todos os estados',
  allYears: 'Todos os anos',
  allReasons: 'Todos os motivos',
  totals: 'Total',
  donationsCount: 'doações',
  preApproved: 'Pré-aprovada',
  reviewed: 'Revisada e aprovada',
  markReviewed: 'Marcar como revisada',
  unmarkReviewed: 'Voltar a pré-aprovada',
  edit: 'Editar',
  delete: 'Excluir',
  deleting: 'Excluindo...',
  confirmDelete: 'Excluir esta doação e o comprovante?',
  confirmEditReviewed: 'Esta doação já foi revisada. Ao salvar alterações ela volta a pré-aprovada. Continuar?',
  actionError: 'A operação falhou.',
  to: 'Para',
  noReceipt: 'sem comprovante',

  errors: {
    church: 'Selecione a igreja.',
    date: 'Informe a data.',
    dateInFuture: 'A data não pode ser futura.',
    amount: 'Informe um valor maior que zero.',
    reason: 'Selecione o motivo.',
    recipient: 'Informe o destinatário.',
    method: 'Selecione a forma de envio.',
    receipt: 'Anexe o comprovante.'
  } satisfies Record<DonationFormError, string>
};

export type DonationsCopy = typeof pt;

const en: DonationsCopy = {
  title: 'Donations to ICEFLU Brazil',
  intro: 'Record the donations your church sent to ICEFLU Brazil, with proof of payment.',
  introAdmin: 'Donations sent to ICEFLU Brazil by every church. Review them and check the receipts.',
  managersHint: 'Donations are recorded by church managers, assigned in Works → Church managers.',
  loading: 'Loading...',
  loadError: 'Could not load the donations.',
  noPermission: 'This area is for church managers. Ask an administrator to link your account to a church.',

  newDonation: 'Record a donation',
  editDonation: 'Edit donation',
  church: 'Church',
  selectChurch: 'Select church...',
  date: 'Date',
  amount: 'Amount (€)',
  reason: 'Reason',
  selectReason: 'Select reason...',
  reasons: { feitio: 'Feitio coverage', membership: 'Membership', jurua: 'Juruá' },
  recipient: 'Recipient',
  recipientPlaceholder: 'Who received the donation',
  method: 'How it was sent',
  methods: { 'bank-transfer': 'Bank transfer', 'in-person': 'By hand' },
  receipt: { 'bank-transfer': 'Bank transfer statement', 'in-person': 'Recipient\'s receipt' },
  receiptPending: 'Proof of payment',
  receiptPickMethod: 'Choose how it was sent: a bank transfer needs the bank statement; by hand, the receipt signed by the recipient.',
  currentReceipt: 'Current receipt',
  replaceReceiptHint: 'Upload a file only to replace it.',
  save: 'Save donation',
  saving: 'Saving...',
  cancel: 'Cancel',
  saved: 'Donation saved.',
  saveError: 'Could not save the donation.',
  fixErrors: 'Fix the highlighted fields.',

  donations: 'Donations',
  noDonations: 'No donations recorded yet.',
  allChurches: 'All churches',
  allStatuses: 'All statuses',
  allYears: 'All years',
  allReasons: 'All reasons',
  totals: 'Total',
  donationsCount: 'donations',
  preApproved: 'Pre-approved',
  reviewed: 'Reviewed and approved',
  markReviewed: 'Mark reviewed',
  unmarkReviewed: 'Back to pre-approved',
  edit: 'Edit',
  delete: 'Delete',
  deleting: 'Deleting...',
  confirmDelete: 'Delete this donation and its receipt?',
  confirmEditReviewed: 'This donation was already reviewed. Saving changes sends it back to pre-approved. Continue?',
  actionError: 'The operation failed.',
  to: 'To',
  noReceipt: 'no receipt',

  errors: {
    church: 'Select the church.',
    date: 'Enter the date.',
    dateInFuture: 'The date cannot be in the future.',
    amount: 'Enter an amount above zero.',
    reason: 'Select the reason.',
    recipient: 'Enter the recipient.',
    method: 'Select how it was sent.',
    receipt: 'Attach the proof of payment.'
  }
};

const es: DonationsCopy = {
  title: 'Donaciones a ICEFLU Brasil',
  intro: 'Registre las donaciones que su iglesia envió a ICEFLU Brasil, con el comprobante.',
  introAdmin: 'Donaciones enviadas a ICEFLU Brasil por todas las iglesias. Revíselas y compruebe los comprobantes.',
  managersHint: 'Las donaciones las registran los gestores de las iglesias, asignados en Trabajos → Gestores de las iglesias.',
  loading: 'Cargando...',
  loadError: 'Error al cargar las donaciones.',
  noPermission: 'Esta área es para los gestores de las iglesias. Pida a un administrador que vincule su cuenta a una iglesia.',

  newDonation: 'Registrar donación',
  editDonation: 'Editar donación',
  church: 'Iglesia',
  selectChurch: 'Seleccionar iglesia...',
  date: 'Fecha',
  amount: 'Importe (€)',
  reason: 'Motivo',
  selectReason: 'Seleccionar motivo...',
  reasons: { feitio: 'Cobertura del feitio', membership: 'Asociativo', jurua: 'Juruá' },
  recipient: 'Destinatario',
  recipientPlaceholder: 'Quién recibió la donación',
  method: 'Forma de envío',
  methods: { 'bank-transfer': 'Transferencia bancaria', 'in-person': 'En mano' },
  receipt: { 'bank-transfer': 'Comprobante bancario', 'in-person': 'Recibo del destinatario' },
  receiptPending: 'Comprobante',
  receiptPickMethod: 'Elija la forma de envío: una transferencia requiere el comprobante bancario; en mano, el recibo firmado por el destinatario.',
  currentReceipt: 'Comprobante actual',
  replaceReceiptHint: 'Suba un archivo solo para sustituirlo.',
  save: 'Guardar donación',
  saving: 'Guardando...',
  cancel: 'Cancelar',
  saved: 'Donación guardada.',
  saveError: 'Error al guardar la donación.',
  fixErrors: 'Corrija los campos resaltados.',

  donations: 'Donaciones',
  noDonations: 'Todavía no hay donaciones registradas.',
  allChurches: 'Todas las iglesias',
  allStatuses: 'Todos los estados',
  allYears: 'Todos los años',
  allReasons: 'Todos los motivos',
  totals: 'Total',
  donationsCount: 'donaciones',
  preApproved: 'Preaprobada',
  reviewed: 'Revisada y aprobada',
  markReviewed: 'Marcar como revisada',
  unmarkReviewed: 'Volver a preaprobada',
  edit: 'Editar',
  delete: 'Eliminar',
  deleting: 'Eliminando...',
  confirmDelete: '¿Eliminar esta donación y su comprobante?',
  confirmEditReviewed: 'Esta donación ya fue revisada. Al guardar cambios vuelve a preaprobada. ¿Continuar?',
  actionError: 'La operación falló.',
  to: 'Para',
  noReceipt: 'sin comprobante',

  errors: {
    church: 'Seleccione la iglesia.',
    date: 'Indique la fecha.',
    dateInFuture: 'La fecha no puede ser futura.',
    amount: 'Indique un importe mayor que cero.',
    reason: 'Seleccione el motivo.',
    recipient: 'Indique el destinatario.',
    method: 'Seleccione la forma de envío.',
    receipt: 'Adjunte el comprobante.'
  }
};

const it: DonationsCopy = {
  title: 'Donazioni all\'ICEFLU Brasile',
  intro: 'Registra le donazioni che la tua chiesa ha inviato all\'ICEFLU Brasile, con la ricevuta.',
  introAdmin: 'Donazioni inviate all\'ICEFLU Brasile da tutte le chiese. Revisionale e controlla le ricevute.',
  managersHint: 'Le donazioni le registrano i gestori delle chiese, assegnati in Lavori → Gestori delle chiese.',
  loading: 'Caricamento...',
  loadError: 'Errore nel caricamento delle donazioni.',
  noPermission: 'Quest\'area è per i gestori delle chiese. Chiedi a un amministratore di collegare il tuo account a una chiesa.',

  newDonation: 'Registra donazione',
  editDonation: 'Modifica donazione',
  church: 'Chiesa',
  selectChurch: 'Seleziona chiesa...',
  date: 'Data',
  amount: 'Importo (€)',
  reason: 'Causale',
  selectReason: 'Seleziona causale...',
  reasons: { feitio: 'Copertura feitio', membership: 'Associativo', jurua: 'Juruá' },
  recipient: 'Destinatario',
  recipientPlaceholder: 'Chi ha ricevuto la donazione',
  method: 'Modalità di invio',
  methods: { 'bank-transfer': 'Bonifico', 'in-person': 'A mano' },
  receipt: { 'bank-transfer': 'Contabile della banca', 'in-person': 'Ricevuta del destinatario' },
  receiptPending: 'Ricevuta',
  receiptPickMethod: 'Scegli la modalità di invio: per un bonifico serve la contabile della banca; a mano, la ricevuta firmata dal destinatario.',
  currentReceipt: 'Ricevuta attuale',
  replaceReceiptHint: 'Carica un file solo per sostituirla.',
  save: 'Salva donazione',
  saving: 'Salvataggio...',
  cancel: 'Annulla',
  saved: 'Donazione salvata.',
  saveError: 'Errore nel salvataggio della donazione.',
  fixErrors: 'Correggi i campi evidenziati.',

  donations: 'Donazioni',
  noDonations: 'Nessuna donazione registrata.',
  allChurches: 'Tutte le chiese',
  allStatuses: 'Tutti gli stati',
  allYears: 'Tutti gli anni',
  allReasons: 'Tutte le causali',
  totals: 'Totale',
  donationsCount: 'donazioni',
  preApproved: 'Pre-approvata',
  reviewed: 'Revisionata e approvata',
  markReviewed: 'Segna come revisionata',
  unmarkReviewed: 'Torna a pre-approvata',
  edit: 'Modifica',
  delete: 'Elimina',
  deleting: 'Eliminazione...',
  confirmDelete: 'Eliminare questa donazione e la sua ricevuta?',
  confirmEditReviewed: 'Questa donazione è già stata revisionata. Salvando le modifiche torna pre-approvata. Continuare?',
  actionError: 'L\'operazione non è riuscita.',
  to: 'A',
  noReceipt: 'senza ricevuta',

  errors: {
    church: 'Seleziona la chiesa.',
    date: 'Indica la data.',
    dateInFuture: 'La data non può essere futura.',
    amount: 'Indica un importo maggiore di zero.',
    reason: 'Seleziona la causale.',
    recipient: 'Indica il destinatario.',
    method: 'Seleziona la modalità di invio.',
    receipt: 'Allega la ricevuta.'
  }
};

export const donationsCopyByLocale: Record<SiteLocale, DonationsCopy> = { pt, en, es, it };
